ProwayWebMvc/Controllers/CalculadoraController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProwayWebMvc.Controllers
{
    [Route("calculadora")]
    public class CalculadoraController : Controller
    {
        
        [HttpGet]
        public IActionResult Index() 
        { 
            return View();
        }

        [HttpGet]
        [Route ("somar")]
        public IActionResult SomarCalculadora()
        {
            return View();
        }

        [HttpGet]
        [Route("subtrair")]
        public IActionResult SubtrairCalculadora()
        {
            return View("subtrair");
        }

        [HttpGet]
        [Route("sum")]

        public IActionResult sum (
            [FromQuery] int numero01,
            [FromQuery] int numero02)
        {
            var soma = numero01 + numero02;
            return Ok($"Soma: {soma} ");
        }

        [HttpGet]
        [Route("CalcularImc")]
        public IActionResult CalcularImc()
        {
            return View();
        }

        [HttpGet]
        [Route("ProcessImc")]
        public IActionResult ProcessImc(
            [FromQuery] double peso,
            [FromQuery] double altura,
            [FromQuery] int idade,
            [FromQuery] string nome) 
        {
            var imc = peso / (altura * altura);
            return Ok($"Nome: {nome} de Idade: {idade} com IMC: {imc}");
        }

        [HttpPost]
        [Route("ProcessImc")]
        public IActionResult ProcessImcPost(
            [FromForm] double peso,
            [FromForm] double altura,
            [FromForm] int idade,
            [FromForm] string nome)
        {
            var imc = peso / (altura * altura);
            return Ok($"Nome: {nome} de Idade: {idade} com IMC: {imc}");
        }


    }   
}

ProwayWebMvc/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using ProwayWebMvc.Models.Categoria;
using SupermercadoServicos.Dtos.Categorias;
using SupermercadoServicos.Interface;
using SupermercadoServicos.Servicos;

namespace ProwayWebMvc.Controllers
{
    [Route("categoria")]
    public class CategoriaController : Controller
    {
        private readonly ICategoriaServico _categoriaServico;
        public CategoriaController()
        {
            _categoriaServico = new CategoriaServico();
        }
        public IActionResult Index()
        {
            var categoriaDtos = _categoriaServico.ObterTodos();
            var viewModels = new List<CategoriaIndexViewModel>();
            foreach(var dto in categoriaDtos)
            {
                var viewModel = new CategoriaIndexViewModel
                {
                    Id = dto.Id,
                    Nome = dto.Nome,
                };
                viewModels.Add(viewModel);
            }
            return View(viewModels);
        }

        [HttpGet("novo")]
        public IActionResult Novo()
        {
            var viewModel = new CategoriaCadastrarViewModel();
            return View(viewModel); 
        }

        [HttpPost("novo")]
        public IActionResult Create([FromForm] CategoriaCadastrarViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Novo", viewModel);
            }

            var dto = new CategoriaCadastrarDto
            {
                Nome = viewModel.Nome,
            };
              
            var id = _categoriaServico.Cadastrar(dto);

            return RedirectToAction("Index");
        }

        [HttpGet("apagar")]
        public IActionResult Apagar([FromQuery] int id)
        {
            _categoriaServico.Apagar(id);

            return RedirectToAction("Index");
        }

        [HttpGet("editar")]

        public IActionResult Editar([FromQuery] int id)
        {
            var categoria = _categoriaServico.ObterPorId(id);

            var vielwModel = new CategoriaEditarViewModel
            {
                Id = categoria.Id,
                Nome = categoria.Nome,
            };

            return View(vielwModel);
        }

        [HttpPost("editar")]

        public IActionResult Update([FromForm] CategoriaEditarViewModel viewModel)

        {
            if (!ModelState.IsValid)
            {
                return View("Editar" , viewModel);
            }
            var categoriaEditarDto = new CategoriaEditarDto
            {
                Nome = viewModel.Nome,
                Id = viewModel.Id,
            };

            _categoriaServico.Editar(categoriaEditarDto);

            return RedirectToAction("index");
        }
    }
}

ProwayWebMvc/Controllers/EstanteController.cs
using Microsoft.AspNetCore.Mvc;
using ProwayWebMvc.Models.Categoria;
using ProwayWebMvc.Models.Estante;
using SupermercadoServicos.Dtos.Estantes;
using SupermercadoServicos.Interface;
using SupermercadoServicos.Servicos;

namespace ProwayWebMvc.Controllers
{
    [Route("estante")]
    public class EstanteController : Controller
    {
        private readonly IEstanteServico _estanteServico;
        public EstanteController()
        {
            _estanteServico = new EstanteServico();
        }
        public IActionResult Index()
        {
            var estanteDtos = _estanteServico.ObterTodos();
            var viewModels = new List<EstanteIndexViewModel>();
            foreach(var dto in estanteDtos)
            {
                var viewModel = new EstanteIndexViewModel
                {
                    Id = dto.Id,
                    Nome = dto.Nome,
                    Sigla = dto.Sigla
                };
                viewModels.Add(viewModel);
            }
            return View(viewModels);
        }

        [HttpGet("novo")]
        public IActionResult novo()
        {
            var viewModel = new EstanteCadastrarViewModel();
            return View(viewModel);
        }


        [HttpPost("novo")]
        public IActionResult Create([FromForm] EstanteCadastrarViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("Novo", viewModel);
            }

            var dto = new EstanteCadastrarDto
            {
                Nome = viewModel.Nome,
            };

            var id = _estanteServico.Cadastrar(dto);

            return RedirectToAction("Index");
        }

        [HttpGet("editar")]
        public IActionResult Editar([FromQuery]int id)
        {
            var estante = _estanteServico.ObterPorId(id);

            var vielwModel = new CategoriaEditarViewModel
            {
                Id = estante.Id,
                Nome = estante.Nome,
            };

            return View(vielwModel);
        }

        [HttpPost("editar")]
        public IActionResult Update([FromQuery] EstanteEditarViewModel viewModel)

        {
            if (!ModelState.IsValid)
            {
                return View("Editar", viewModel);
            }
            var estanteEditarDto = new EstanteEditarDto
            {
                Nome = viewModel.Nome,
                Id = viewModel.Id,
            };

            _estanteServico.Editar(estanteEditarDto);

            return RedirectToAction("index");
        }
        [HttpGet("apagar")]
        public IActionResult Apagar([FromQuery] int id)
        {
            _estanteServico.Apagar(id);

            return RedirectToAction("Index");
        }

    }
}

ProwayWebMvc/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProwayWebMvc.Models.Produtos;
using SupermercadoServicos.Dtos.Categorias;
using SupermercadoServicos.Dtos.Produtos;
using SupermercadoServicos.Interface;
using SupermercadoServicos.Servicos;

namespace ProwayWebMvc.Controllers
{
    [Route("produto")]
    public class ProdutoController : Controller
    {
        
        private readonly IProdutoServico _produtoServico;
        private readonly ICategoriaServico _categoriaServico;

        public ProdutoController()
        {
            _produtoServico = new ProdutoServico();
            _categoriaServico = new CategoriaServico();
        }
        public IActionResult Index()
        {
            var produtosDtos = _produtoServico.ObterTodos();
            var produtoIndexViewModels = ProdutoIndexViewModel.ConstruirCom(produtosDtos);
            
            return View(produtoIndexViewModels);
        }
        [HttpGet("novo")]
        public IActionResult Cadastrar()

        {
            PreecherCategoriaViewBag();

            var produtoCadastrarViewModel = new ProdutoCadastrarViewModel();
            return View(produtoCadastrarViewModel);

        }

        private void PreecherCategoriaViewBag()
        {
            var categoriaDtos = _categoriaServico.ObterTodos();
            ViewBag.CategoriaDtos = ConstrirSelectListItemDasCategorias(categoriaDtos);
        }

        private List<SelectListItem> ConstrirSelectListItemDasCategorias(
            List<CategoriaDto> categoriaDtos)
        {
            var items = new List<SelectListItem>();
            foreach(var dto in categoriaDtos)
                items.Add(new SelectListItem(dto.Nome, dto.Id.ToString()));
            return items;
        }

        [HttpPost("novo")]
        public IActionResult Cadastrar([FromForm] ProdutoCadastrarViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                PreecherCategoriaViewBag();
                return View(viewModel);
            }
            var produtoDto = new ProdutoCadastrarDto
            {
                Nome = viewModel.Nome,
                CategoriaId = viewModel.CategoriaId.GetValueOrDefault(),
                PrecoUnitario = viewModel.PrecoUnitario.GetValueOrDefault(),
                DataVencimento = viewModel.DataVencimento.GetValueOrDefault(),
                Observacao = viewModel.Observacao
            };
            var id = _produtoServico.Cadastrar(produtoDto);
            return RedirectToActionPreserveMethod("Index");
        }

        [HttpGet("apagar")]
        public IActionResult Apagar([FromQuery]int id)
        {
            _produtoServico.Apagar(id);
            return RedirectToAction(nameof(Index));        }
        }
}

ProwayWebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProwayWebMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProwayWebMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProwayWebMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li><li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categoria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estante" asp-action="Index">Estante</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProwayWebMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/ae7072820f.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>